# Generated by Django 3.2.8 on 2021-10-23 14:21

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name: ')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last Name: ')),
                ('contact_no', models.CharField(max_length=50, verbose_name='Contact number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Id: ')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, verbose_name='Grade: ')),
                ('section', models.CharField(max_length=50, verbose_name='Section: ')),
                ('roll_no', models.IntegerField(blank=True, null=True)),
                ('student_id', models.IntegerField(default=builtins.id, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Id:')),
            ],
        ),
    ]
