# Generated by Django 3.2.8 on 2021-10-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name: ')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last Name: ')),
                ('address', models.CharField(max_length=100, verbose_name='Address: ')),
                ('date_of_birth', models.DateField(verbose_name='DOB: ')),
            ],
        ),
        migrations.CreateModel(
            name='UserAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.userinfo')),
                ('parents_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admission.parentsinfo')),
                ('student_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.studentinfo')),
            ],
        ),
    ]
