# Generated by Django 3.2.8 on 2021-10-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_useradmission_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
