# Generated by Django 3.2.8 on 2021-10-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_studentinfo_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
