# Generated by Django 3.2.8 on 2021-10-31 07:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_studentinfo_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('m_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Middle Name')),
                ('l_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('short_name', models.CharField(max_length=50)),
            ],
        ),
    ]
