# Generated by Django 3.2.8 on 2021-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_teachersinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersinfomodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
    ]
