# Generated by Django 3.2.8 on 2021-10-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('grade', models.IntegerField(verbose_name='Grade')),
                ('sub1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 1')),
                ('sub2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 2')),
                ('sub3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 3')),
                ('sub4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 4')),
                ('sub5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 5')),
                ('sub6', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 6')),
                ('sub7', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 7')),
                ('sub8', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 8')),
                ('sub9', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 9')),
                ('sub10', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 10')),
                ('sub11', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 11')),
                ('sub12', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject 12')),
            ],
        ),
    ]
