# Generated by Django 3.2.8 on 2021-11-01 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_alter_studentinfo_course'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='tec1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub1', to='admission.teachersinfomodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tec10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub10', to='admission.teachersinfomodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tec11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub11', to='admission.teachersinfomodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tec12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub12', to='admission.teachersinfomodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tec2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub2', to='admission.teachersinfomodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tec3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub3', to='admission.teachersinfomodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tec4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub4', to='admission.teachersinfomodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tec5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub5', to='admission.teachersinfomodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tec6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub6', to='admission.teachersinfomodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tec7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub7', to='admission.teachersinfomodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tec8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub8', to='admission.teachersinfomodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='tec9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub9', to='admission.teachersinfomodel'),
        ),
    ]
