# Generated by Django 3.2.8 on 2021-10-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_auto_20211019_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
